---
- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/install_composer.php

- name: Run Composer installer
  command: php /tmp/install_composer.php --install-dir=/usr/local/bin --filename=composer
