---
# handlers file for roles/laravel

- name: Restart PHP-FPM service
  service:
    name: "php{{ laravel_php_version }}-fpm"
    state: restarted

- name: Restart Nginx service
  service:
    name: nginx
    state: restarted
